// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy_Y-NE9GV07mEvAPiWCQOUK-Q4xuYgdU',
    appId: '1:540030725712:web:6275f3593060ddd104ab55',
    messagingSenderId: '540030725712',
    projectId: 'health-app-1e75d',
    authDomain: 'health-app-1e75d.firebaseapp.com',
    storageBucket: 'health-app-1e75d.appspot.com',
    measurementId: 'G-CGYGFZTEM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EPeDuMDWcK-uynUxzX5YwKxITZ2P0nI',
    appId: '1:540030725712:android:ca1fb91d337d93e904ab55',
    messagingSenderId: '540030725712',
    projectId: 'health-app-1e75d',
    storageBucket: 'health-app-1e75d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs3DS9nnQNeLGemslNYVVHYNpKmu03bRY',
    appId: '1:540030725712:ios:0c60f649ee2f5e2f04ab55',
    messagingSenderId: '540030725712',
    projectId: 'health-app-1e75d',
    storageBucket: 'health-app-1e75d.appspot.com',
    androidClientId: '540030725712-99gcj0t8nihkk0de72kcaskaolsgkv2i.apps.googleusercontent.com',
    iosClientId: '540030725712-a19trld44g04tr1hht6442281dtfshhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs3DS9nnQNeLGemslNYVVHYNpKmu03bRY',
    appId: '1:540030725712:ios:4178de6e895da17904ab55',
    messagingSenderId: '540030725712',
    projectId: 'health-app-1e75d',
    storageBucket: 'health-app-1e75d.appspot.com',
    androidClientId: '540030725712-99gcj0t8nihkk0de72kcaskaolsgkv2i.apps.googleusercontent.com',
    iosClientId: '540030725712-lobgb8q34ucdl1u0h60g6lvubu061qc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApp.RunnerTests',
  );
}
